### ISSUE TITLE
tooltips

### ISSUE THREAD

**Issue by dwightkelly** [shawmut/DataPreflight#17]
A couple of suggestions on tooltips
1. The non-Header hash tooltips are rendered too narrow and cause flickering when hover-overed.
2. The tooltips for data cells is not needed since it just displays the same value as cell

Firefox 45.0.1
Chrome 49.0.2623.87
Mac OS X 10.11.3

**Comment by dominickp** [comment]
Regarding #2, the tooltip was there since data does get truncated after a certain amount of characters. The problem is, the tooltips are truncated as well so it's pretty useless.

I'll work on UI fixes for these soon.

**Comment by dominickp** [comment]
Complete in 0c0a9a669a0d1dca5afdf19a7655e84bb7c36bc7
