### ISSUE TITLE
Don't show "Middle" and "Last" columns if file only has 1 or 2 columns

### ISSUE THREAD

**Issue by dwightkelly** [shawmut/DataPreflight#22]
I was confused that the First, Middle and Last columns in the data integrity check section had the same values. Thought maybe there was a logic bug. However, it turned out the file only had a header line and 1 data row. The table header did say "row 2" for all 3 columns but I found it confusing.

**Comment by dominickp** [comment]
Yeah, makes sense. I used some division with rounding to come up with those positions. So if the file has < 3 records, I'll just display the records, removing middle first, then last.

**Comment by dominickp** [comment]
Complete in 10d9652d4c339a1a2c4056228522481a65fd0606
