### ISSUE TITLE
question about row count

### ISSUE THREAD

**Issue by dwightkelly** [shawmut/DataPreflight#25]
If a file has a header line, should the first data row be row 1 or 2? Currently you show row 2.

**Comment by dominickp** [comment]
Row 2, right? The row positions are to help the person spot-checking the database to know what record to refer to in something like Excel. In Excel, the first data row would be Row 2. In some VDP/data software, it' smart enough so it will display the first data record as Row 1. I'd say it's correct the way it is, but it's debatable.

One thing to note is, the data preflight requires a header row. It will always assume the first row is the header. I was trying to think of how it should work if there wasn't a header and I haven't come up with a great solution yet. Any thoughts?

**Comment by dwightkelly** [comment]
OK, using the term "row" it's probably correct. If you were using "record" then not. No change required.

As for header line being required, I think that's OK. It's required for most VDP solutions.
