### ISSUE TITLE
What does each DIC header line hash represent?

### ISSUE THREAD

**Issue by dwightkelly** [shawmut/DataPreflight#29]
Not sure what the hash image for each of the header lines in the DIC table mean? I would have expected "PriorCarrier1" and "PriorPolicy6" to have different hashes if was calculated from just the column name. Instead it appears to include the data values also.

**Comment by dominickp** [comment]
It's hashing the column contents completely, minus the header. Said another way, if you had two columns "ColA" and "ColB" and each had the same data, it would show the same hash. It's purpose is to identify when any of the data within the column changes.
